# Generated by Django 5.1.5 on 2025-02-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_cases_table_alter_items_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/profile_images/')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cases', models.ManyToManyField(blank=True, to='cases.cases')),
                ('items', models.ManyToManyField(blank=True, to='cases.items')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
