# Generated by Django 5.1.5 on 2025-02-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_cases_options_alter_items_options_cases_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cases',
            table='Case',
        ),
        migrations.AlterModelTable(
            name='items',
            table='Item',
        ),
    ]
